### ISSUE TITLE
comments

### ISSUE THREAD

**Issue by capslock321** [lasscat/namemcpy#2]
I have a few comments on your, api
some good things:
your api, is one of the first and is already on pypi. great job
the amount of comments detailing what you are doing
bad things:
functions names are extremely long, and can definitly be condensed for easier usage. eg printFriendListUsernameOutputUsername
lack of functionality, and multiple functions can be put togehter as one eg. printFriendListUsernameOutputUsername
poor documentation, does not explain what it output, eg dict, list
and a lack of a requrements.txt EDIT: i did not see the install.txt
you may object to some of them, but this is my opinion or your api
good job tho

**Comment by lasscat** [comment]
Yea I was thinking about that I will try to shorten them in the next update.

**Comment by lasscat** [comment]
Thank you for the tips.

**Comment by capslock321** [comment]
no prob

**Comment by lasscat** [comment]
Okay what do you think for my maybe new system to get rid of the long function names.
def printFriendList(self, playerInput=False, uuidInput=False, playerOutput=False, uuidOutput=False):
Basically how this works is that you enter the player name in the playerinput for input vice versa, and the same thing for output?

**Comment by capslock321** [comment]
@lasscat to be honest, i am not a fan of printFriendsList, it in my opinion is too long of a name and can be massively shortened to .friends(). uuid and names can be combined into one function, because if you search namemc.com/name/uuid-192-djd
is the same as namemc.com/name/lasscat. you can access the websites using requests.get then getting the title of the websites name to get the name. this in my opinion is more efficient

**Comment by capslock321** [comment]
also i am also making an wrapper for name mc, cuz i got bored
started 5 days ago to be exact

**Comment by lasscat** [comment]
Not to be rude why would you replicate a project that I am doing?

**Comment by capslock321** [comment]
It was really a small project to keep me busy, before this i was very bored, doing little things that would only take 1 day to complete. This project also taught me how to write docs, so yeah.

**Comment by capslock321** [comment]
its best if you take yours down too but, hey im not the boss of you lol

**Comment by capslock321** [comment]
IF you choose to keep going, a good way to improve your docs is to use sphinx https://www.sphinx-doc.org/en/master/ 
its a free documentation maker and makes very nice looking docs. You just have to put doc strings everywhere which is annoying to me.

**Comment by lasscat** [comment]
Ok thank you for clearing things up feel free to work on my project and I will work on yours

**Comment by capslock321** [comment]
ill bring my repo to public, i dont think ill work on it anymore, so yeah. @lasscat ill take it down when the owner of namemc tell me to take it down, else i am not going to

**Comment by lasscat** [comment]
Ok but why would the owner of namemc say to take it down?

**Comment by capslock321** [comment]
when you are webscraping, you are making request to the server. this can cause unesscary traffic and may block (depending on how its used) actual "people" from accessing the site. which is why some websites check for your browser to see if it is via a supported browser, not python etc.

**Comment by capslock321** [comment]
i really dont see what is the problem tho. if a person makes too many requests, just block the ip lol.

**Comment by lasscat** [comment]
Oh I understand sorry I misunderstood
