### ISSUE TITLE
Import module failed

### ISSUE THREAD

**Issue by DarkOnion0** [lasscat/namemcpy#3]
# System Info
- **os:** ArchLinux
- **python version:** 3.9.1 in virtualenv

# Problem 
- Can not import the `namemcpy` module after installed it successfully with the `pip install namemcpy` command

**Comment by lasscat** [comment]
Ok I merged the requests if the issues is not fixed, please tell me so I can resolve.

**Comment by lasscat** [comment]
Also I will add you to the credits on the read me thanks for your support.
