### ISSUE TITLE
"ValueError: list.remove(x): x not in list"

### ISSUE THREAD

**Issue by ghost** [lasscat/namemcpy#6]
```Traceback (most recent call last):

  File ".........", line 343, in _run_event

    await coro(*args, **kwargs)
  File "....\main.py", line 51, in on_message
    skin = api.playerSkins(username=message.content.split()[2])
  File "..........\namemc.py", line 286, in playerSkins
    skin_hash_list.remove('javascript:void(0)') # just have to get rid of something that stays in the code idk y
ValueError: list.remove(x): x not in list

```

Please help, I tried fixing the issue myself but nothing really worked.

**Comment by lasscat** [comment]
I'll look into it.

**Comment by lasscat** [comment]
Question, can you give me the code you were using in that segment so I can see what caused the issue.

**Comment by ghost** [comment]
> Question, can you give me the code you were using in that segment so I can see what caused the issue.

Unfortunately I can't really show much of my code since I am using a new API now, but I did add `api = namemc.namepy()` to the beginning of my code and `message.content.split()[2]` was a valid Minecraft username.

**Comment by ghost** [comment]
I'm pretty sure the issue resides in where you try removing `javascript:void(0)` from `skin_hash_list`, but it's actually not always there. Also noticed it only worked with my skin and no one else's?

**Comment by lasscat** [comment]
What is your skin hash?

**Comment by lasscat** [comment]
Ok I found that this issue occurs when the player has many amount of skins

**Comment by lasscat** [comment]
When a player has a large amount of skins it will not display the javascript error I will fix this

**Comment by lasscat** [comment]
Fixed will be rolling out the update!

**Comment by lasscat** [comment]
Fixed

**Comment by ghost** [comment]
Thank you! I was really confused why it only worked on my skin, lol

**Comment by lasscat** [comment]
Sadly there is an bug where it does not show all the skins if you have a large amount of skins currently I will have to fix.

**Comment by lasscat** [comment]
Its probably the scraping as when you do it, it does not show all the skins but I know of a fix on how I can fix this

**Comment by ghost** [comment]
May I ask why you have to scrape it and not get it directly from the API? After all this is an API wrapper

**Comment by lasscat** [comment]
Sadly, namemc or mojang api does not offer these features with there api so I have to resort to scraping.

**Comment by ghost** [comment]
Alright, I guess that's understandable.

**Comment by lasscat** [comment]
Yea I want them to add more api features. :/
