### ISSUE TITLE
Cannot Import Module

### ISSUE THREAD

**Issue by aaroncf2008** [lasscat/namemcpy#9]
When using I get this error, after successfully installing it

Traceback (most recent call last):
  File "main.py", line 5, in <module>
    import namemcpy
ModuleNotFoundError: No module named 'namemcpy'

**Comment by lasscat** [comment]
Try this from 
`from namemcpy import namepy`

**Comment by aaroncf2008** [comment]
this sadly doesn't work either

**Comment by TheOnlyWayUp** [comment]
> When using I get this error, after successfully installing it
> 
> Traceback (most recent call last): File "main.py", line 5, in import namemcpy ModuleNotFoundError: No module named 'namemcpy'

@aaroncf2008 Is this issue resolved? If not, could you tell us what OS you're on and what version of python you're using, as well as the command you used to install namemcpy?

I'm thinking it could be a version mismatch, pip is installing to another version other than what you're currently using. You can try running `pythonX.Y -m pip install namemcpy` where X.Y are your version numbers (eg. 3.10)

**Comment by Anino75** [comment]
Hey, are you still working on it ? I have the same issue here, I'm on windows and installed with `py -m pip install namemcpy`

**Comment by lasscat** [comment]
I have not worked on this project in a while , i think u can just download the .py and put it in the same folder with ur code and try importing it?

**Comment by TheOnlyWayUp** [comment]
> > When using I get this error, after successfully installing it
> > Traceback (most recent call last): File "main.py", line 5, in import namemcpy ModuleNotFoundError: No module named 'namemcpy'
> 
> @aaroncf2008 Is this issue resolved? If not, could you tell us what OS you're on and what version of python you're using, as well as the command you used to install namemcpy?
> 
> I'm thinking it could be a version mismatch, pip is installing to another version other than what you're currently using. You can try running `pythonX.Y -m pip install namemcpy` where X.Y are your version numbers (eg. 3.10)

kek, I should've read the code first

Made a PR to fix this
